### ISSUE TITLE
关于嵌套ner数据集

### ISSUE THREAD

**Issue by tricktreat** [thunlp/PL-Marker#1]
你好，感谢分享出色的工作！

关于数据集有个问题咨询一下。ace04和ace05有head版本和mention版本，head版本的实体嵌套率基本为0。论文中报告的这两个数据集上的结果都上了90，比一般方法高了很多，请问论文中使用的ace04和ace05是mention版本的嵌套数据集么？

**Comment by YeDeming** [comment]
同学你好，

应该不是嵌套版本的，我用的用作关系抽取的版本，来自于[DyGIE](https://github.com/luanyi/DyGIE/tree/master/preprocessingl)，基本保留了所有NER信息，没有经过数据筛选，同时论文中表4的baseline也是用的这个划分

祝好

**Comment by tricktreat** [comment]
好的，感谢解答~
