### ISSUE TITLE
关于ACE数据预处理的问题

### ISSUE THREAD

**Issue by lairunlin** [thunlp/PL-Marker#10]
冒昧问一下。关于ACE04/05数据集，代码中没有给出相应的数据预处理代码，paper中也只提到划分方法。所以，请问是否可以公开代码预处理代码？如有不便，是否可以给出一两条的数据集范例？非常感谢，冒昧之处请原谅。

https://github.com/thunlp/PL-Marker/blob/91b03f3ff58ad29fd7b9920a954a02d12756f05d/run_acener.py#L171-L193

**Comment by YeDeming** [comment]
你好，数据预处理用的DyGIE的代码 https://github.com/luanyi/DyGIE/tree/master/preprocessing

**Comment by lairunlin** [comment]
对于上述提到的代码，仍然有疑问，请指教。
在`run.zsh`（如图2红框）中需要处理`*.split.txt`，但在`conll2txt.py`（如图1）中并没有生成`*.split.txt`的操作，但是从shell命令传入`conll2txt.py`的参数中却有相应的`*.split.txt`，这是否是代码的问题？或者是在其他我没注意到的地方有生成`*.split.txt`？

![1](https://user-images.githubusercontent.com/26412312/150311936-66de3d55-8450-420d-8f95-181f89d259f5.png)

![2](https://user-images.githubusercontent.com/26412312/150311972-dc3bb3d5-da4f-4674-bcff-a6ce7ae73acd.png)

**Comment by YeDeming** [comment]
我猜这个命令里的>应该是重定向输出流到文件吧， 我这边是很久之前直接运行就预处理完了，不太记得清楚了

**Comment by lairunlin** [comment]
好的，感谢！
