### ISSUE TITLE
cannot import name 'BertForNER'

### ISSUE THREAD

**Issue by sculichen** [thunlp/PL-Marker#16]
cannot import name 'BertForNER'

**Comment by YeDeming** [comment]
Do you execute the command `pip3 install --editable transformers` ?

**Comment by ouyang982020** [comment]
> Do you execute the command `pip3 install --editable transformer

**Comment by ouyang982020** [comment]
> Do you execute the command `pip3 install --editable transformers` ?

![image](https://user-images.githubusercontent.com/75766732/165201517-a8c67b6a-ee97-484b-aa00-0afa5d940422.png)
想请教一下这个问题怎么解决呢。
![image](https://user-images.githubusercontent.com/75766732/165202004-a56dd0e2-fc52-4e8d-bd34-4a2fe234b914.png)
然后我到文件夹路径下载本项目的transformers文件夹，里面报错更多了

**Comment by ouyang982020** [comment]
![image](https://user-images.githubusercontent.com/75766732/165218008-0ff21c47-4ebf-4fe3-8d19-8e78e165203b.png)
这个问题什么问题呀

**Comment by YeDeming** [comment]
同学你好，先需要下载这个github项目的代码，并到下载的目录中执行
