### ISSUE TITLE
请问怎么处理中文数据集

### ISSUE THREAD

**Issue by Macvh** [thunlp/PL-Marker#19]
您好，我按照readme中给的数据格式样例处理好中文数据集后，在评估的时候assert(tot_recall==len(golden_labels))地方报错，不知道什么原因，注释掉后会出现F1=0，loss=0的情况，请问是我数据集处理的有问题吗，中文数据集改怎么处理，期待作者的回复，万分感谢

**Comment by YeDeming** [comment]
请问可以将你处理好的数据样本发到我的邮箱yedeming001@163.com吗

**Comment by guanxichouqu** [comment]
> 您好，我按照readme中给的数据格式样例处理好中文数据集后，在评估的时候assert（tot_recall==len（golden_labels））地方报错，不知道什么原因，注释掉后会出现F1=0，loss=0的情况，请问是我数据集处理的有问题吗，中文数据集改怎么处理，期待作者的回复，万分感谢

你好 我也想在中文数据集上进行应用 可以向您学习一下吗
