### ISSUE TITLE
请教一下，是否能处理跨句的关系抽取

### ISSUE THREAD

**Issue by OPilgrim** [thunlp/PL-Marker#20]
如题，代码正在研究，但还是希望作者能给个快速的回复，假设输入是一句一句地输入，这个代码是只能抽取出单句中包含的关系，还是可以抽取出跨句的关系？非常感谢！

**Comment by YeDeming** [comment]
这个代码是只考虑了单句内关系，因为所用的数据集都只涉及单句内关系，模型理论上可以拓展到跨句

**Comment by OPilgrim** [comment]
非常感谢，我还有一个疑惑，关系抽取任务，subject和object的span是给定的吗，即要么先做NER，要么给定标准的NER？需要预测的其实只有关系，还是说span也是需要预测的？

**Comment by YeDeming** [comment]
这篇论文要先做NER，只预测关系，是一个两级系统
