### ISSUE TITLE
512 and 1024?

### ISSUE THREAD

**Issue by Jay0412** [thunlp/PL-Marker#23]
As I know, BERT is limit the position embedding as 512.
However, when I look at the code, I found position id, input id and etc. have 1024 size.
I quite confusing about this concept.
Could you explain about the difference above those?

**Comment by Jay0412** [comment]
+) I have one more question.
As I understand, I think when doing relation extraction this model uses levitated marker.
However, in your script about training re, it uses run_re.py file which seems they don't use a levitated marker.
I wonder what is the difference between run_re.py and run_levitatedpair.py.
Also, could you explain what's the exact meaning of BertForACEBothSub, BertForACEBothOneDropoutSpanSub, BertForACEBothOneDropoutSub, BertForACEBothOneDropoutLeviPair, BertForACEBothOneDropout classes?

**Comment by YeDeming** [comment]
run_levitatedpair.py is for ablation study (two pairs of leviteatd marker) 
BertForACEBothSub, BertForACEBothOneDropoutSpanSub, BertForACEBothOneDropoutSub, BertForACEBothOneDropoutLeviPair, BertForACEBothOneDropout are a serious of attempts, we finally use the default BertForACEBothOneDropoutSub.

**Comment by Jay0412** [comment]
Thank you for answering.
Okay, then does it means BERTForACEBothOneDropoutSub uses levitated marker for relation extraction?
Also, I still want to know about the first question(512 and 1024), could you explain it plz?

**Comment by YeDeming** [comment]
1. BERTForACEBothOneDropoutSub uses a hybrid of solid marker and levitated marker for relation extraction.
2. We set the levitated markers share the same postion id as span boundary tokens.
For example,
tokens:              I like <m> apple pie </m>
position id:       0  1     2       2       3      3  

Though the sequence length > 512, the postion id ranges from 0-512

**Comment by Jay0412** [comment]
Thanks, I understand both of them.
As you explained, I also think position id ranges from 0-512.
However, when I print out the position id shape, it is 1024.
I can't understand, how it can be possible that it has a 1024 shape and also others (input_id, 
![image](https://user-images.githubusercontent.com/43334793/169690822-54de9197-2df6-49f0-a103-96458d877d92.png)

**Comment by YeDeming** [comment]
Transformer can support any length.

**Comment by Jay0412** [comment]
Sorry, I'm a beginner of study NLP...
Could you explain in more detail? I don't get it...
How transformer can support any length even though, BERT limits the position id ranges from 0-512?

**Comment by YeDeming** [comment]
Yes.

**Comment by Jay0412** [comment]
Well...so,,, any explnation???

**Comment by YeDeming** [comment]
BERT limits the position id ranges from 0-512. But we can use the same postion id for different tokens. For example, set 1024 tokens' postion = 0

**Comment by Jay0412** [comment]
Ah..! I understand! Thank you very much for your kind reply :)
