### ISSUE TITLE
re_classifier

### ISSUE THREAD

**Issue by wsh2836741** [thunlp/PL-Marker#31]
感谢您杰出的工作。想问下，关系预测里为什么需要有两个re_classifier（re_classifier_m1和re_classifier_m2）？相当于是subject和object分别计算的吗？传统做法不应该是拼接到一起然后过一个re_classifier多分类吗？

**Comment by YeDeming** [comment]
你好，效果是一样的， W_classifer*[x;y] = W_x*x+W_y*y
