### ISSUE TITLE
documentation how to use pretrained models?

### ISSUE THREAD

**Issue by Hevia** [thunlp/PL-Marker#34]
These models look great! I would love to know if there are any plans on how the wider research community could use these models from your checkpoints? Some examples in the README of running inference through a cli or just via code would be nice. Personally I would love to try them out on my usecase before committing to any training 

Would be awesome if there are any plans to integrate with your other package: https://github.com/thunlp/OpenNRE

**Comment by YeDeming** [comment]
Sorry. I don't plan to integrate the code into OpenNRE right now.

If you encounter any problems with the example commands, please comment here.
