### ISSUE TITLE
NIL实体的作用

### ISSUE THREAD

**Issue by WangSheng21s** [thunlp/PL-Marker#39]
请问在每一句的后面插入NIL实体的作用是什么呢？影响大吗
![image](https://user-images.githubusercontent.com/102408340/200255435-738acba0-b060-4b35-ad65-6948b9e8fbb7.png)

**Comment by YeDeming** [comment]
每个训练样本是RE loss+NER loss，这里相当于单独加了一个只有NER loss的样本，影响不大

**Comment by WangSheng21s** [comment]
re_prediction_scores = m1_scores.unsqueeze(1) + m2_scores

在关系分类判别器中，为什么采用的是单独将sub和obj进行分类得到分数后再相加而不是直接先将sub和obj拼接在一起之后进行分类呢？

**Comment by WangSheng21s** [comment]
为什么会想要单独加一个只有NER loss的样本呢？谢谢！

**Comment by YeDeming** [comment]
有的句子不包含relation，此时就没有触发计算NER loss

**Comment by YeDeming** [comment]
> 

一样的，过线性层的话

**Comment by WangSheng21s** [comment]
好的，太感谢了！
