### ISSUE TITLE
你好，--lminit是一种初始化，类似于prompt，将两个marker分别初始化为单词[MASK]和entity的embedding，能在英文数据集上带来0.1 F1的提升。在中文上可以直接关闭这个选项

### ISSUE THREAD

**Issue by lairunlin** [thunlp/PL-Marker#40]
你好，--lminit是一种初始化，类似于prompt，将两个marker分别初始化为单词[MASK]和entity的embedding，能在英文数据集上带来0.1 F1的提升。在中文上可以直接关闭这个选项

_Originally posted by @YeDeming in https://github.com/thunlp/PL-Marker/issues/32#issuecomment-1219538082_

**Comment by YeDeming** [comment]
?
