### ISSUE TITLE
unused token

### ISSUE THREAD

**Issue by WangSheng21s** [thunlp/PL-Marker#41]
![image](https://user-images.githubusercontent.com/102408340/202171187-38b716a1-5e23-4c11-acdd-bcfab47cf7c2.png)
你好，为什么只在albert模型上用了unused_token呀

**Comment by YeDeming** [comment]
都用上了，bert本身就有unused，albert没有所以往词表里加

**Comment by WangSheng21s** [comment]
谢谢
