### ISSUE TITLE
Example of json format of test set

### ISSUE THREAD

**Issue by 404creep** [thunlp/PL-Marker#43]
Can you provide the json format use case of ace05 test set？because my source dataset format is txt，I need to convert the dataset

**Comment by YeDeming** [comment]
Hi, the format is shown in README.

**Comment by 404creep** [comment]
sorry， the format you have shown is the example of train set?  i want to know the example of test set.

**Comment by YeDeming** [comment]
Data formats for training and test set are the same.

**Comment by guanxichouqu** [comment]
> 抱歉，您显示的格式是火车组的示例？我想知道测试集的例子。

你好 请问可以分享一下格式转换的文件吗 我数据集格式跟原来的也不一样
