### ISSUE TITLE
Packing Schema

### ISSUE THREAD

**Issue by kizunasunhy** [thunlp/PL-Marker#44]
Just a little question. Why do we need to pack according to subjects? Is it possible to pack all the entities with solid markers and concatenate all the possible span pairs at the end of one instance? Is it because of nested NER?
Thank you.

**Comment by YeDeming** [comment]
Sure. This method is adopted by [1].
[1] Denoising relation extraction from document-level distant supervision. Xiao el al.

We applied the leviated markers to generate the span-pair concept in the input rather than the final layer.
