### ISSUE TITLE
关于marker对应的representation的疑问

### ISSUE THREAD

**Issue by lairunlin** [thunlp/PL-Marker#45]
实体识别过程中，使用了一些 [unused] 作为 entity start marker 和 entity end marker的词汇，其中有一个操作是将“entity”和“[MASK]”对应的词向量作为 [unused] 的词向量参与训练。请问，这里用 entity 单词的词向量比较好理解，但是为什么要用 [MASK] 呢？

https://github.com/thunlp/PL-Marker/blob/07fde08d868134ced1d861d17d263d6c782bb420/run_acener.py#L979

https://github.com/thunlp/PL-Marker/blob/07fde08d868134ced1d861d17d263d6c782bb420/run_acener.py#L1000-L1001

**Comment by YeDeming** [comment]
类似于prompt有mask占位符填词

**Comment by lairunlin** [comment]
没理解什么意思，请指教。
从代码上看，分别用 [unused0] 和 [unused1] 来表示 entity start marker 和 entity end marker的，然后又有一个复制词向量的操作（代码如下）
https://github.com/thunlp/PL-Marker/blob/07fde08d868134ced1d861d17d263d6c782bb420/run_acener.py#L1000-L1001

这个操作是用 “entity” 和 “[MASK]” 的词向量来替换原来 [unused0] 和 [unused1] 的词向量，我理解的意思告诉模型候选实体的 start 和 end 的位置在哪。

没有理解您之前的回复 “类似于prompt有mask占位符填词” ，请问可否解惑一下，谢谢。

**Comment by YeDeming** [comment]
想用一些有含义的词初始化一下，选[mask]是因为很多做prompt的工作都会放mask，参考  PTR: prompt tuning with rules for text classification. Han et al.
