### ISSUE TITLE
Single Sentence Comparison

### ISSUE THREAD

**Issue by kizunasunhy** [thunlp/PL-Marker#46]
Hello. Have you tried single sentence implementation on Scierc and compare it with PURE Approximation model?

**Comment by YeDeming** [comment]
I didn't try it. You can set left_context_length = right_context_length =0 to re-run my code

https://github.com/thunlp/PL-Marker/blob/07fde08d868134ced1d861d17d263d6c782bb420/run_re.py#L244-L257

**Comment by kizunasunhy** [comment]
> I didn't try it. You can set left_context_length = right_context_length =0 to re-run my code
> 
> 
> 
> https://github.com/thunlp/PL-Marker/blob/07fde08d868134ced1d861d17d263d6c782bb420/run_re.py#L244-L257
> 
> 
> 
> 

Thank you!
