### ISSUE TITLE
Unable to load model from checkpoint 

### ISSUE THREAD

**Issue by Dimiftb** [thunlp/PL-Marker#5]
Hi there, 

I'm trying to replicate your results, however I'm getting an error, which I'm unsure how to go about solving. This is the error message that I'm getting:

![image](https://user-images.githubusercontent.com/26279721/145022825-557db207-8718-4895-92be-2f6f3ce3e963.png)

I've downloaded roberta-large from the official hugginface repo at: https://huggingface.co/roberta-large/tree/main

Appreciate your help!

**Comment by YeDeming** [comment]
Thanks for your feedback. We have update the downloard method in the README.

Best,
Deming

**Comment by Dimiftb** [comment]
Hi @YeDeming

Thank you for sorting this.
