### ISSUE TITLE
Position_id

### ISSUE THREAD

**Issue by Jay0412** [thunlp/PL-Marker#54]
Hello, I have a question after a long time.
No other than that, I'm rewatching the BERTForSpanNER code, but what's the clear reason why you don't use the position_id only in that code as follows?
![image](https://github.com/thunlp/PL-Marker/assets/43334793/3b810e8a-dc67-4820-8472-fb0fa72d370e)
Is it because we will extract the start and end parts of the span by mention_pos later? Then, why is it used in position_id in BERTForSpanMarkerNER?

In addition, I wonder what the BERTforNER code is for. I don't understand the parts e1_hidden_states and e2_hidden_states. what's the information that they want to extract?

_Originally posted by @Jay0412 in https://github.com/thunlp/PL-Marker/issues/25#issuecomment-1567850120_

**Comment by YeDeming** [comment]
1. if we send postion_ids=None, BERT will use default [0,1,2,3,...]
2. e1_hidden_states for token's start subword, e2 for the end subword

**Comment by Jay0412** [comment]
Thank you for answering! However...

First, I know about the BERT's defulat setting but, the point is why you don't use position id unlike the others? As I saw the other codes they use batch[2] which is from item that made in dataset class part as position id.

Second, then what is the difference between BERTforNER and BERTforSpanNER??
