### ISSUE TITLE
语料选择中文数据集，预训练模型bert-base-Chineseese，效果太差，有哪些步骤需要修改的吗？

### ISSUE THREAD

**Issue by thankslife** [thunlp/PL-Marker#58]
我把语料换成中文数据集CMEIE，预训练模型bert-base-chinese，为什么效果这么差，pure F值还能达到0.6呢，
下面是pl-marker ner结果
{"dev_best_f1": 0.08358639461309555, "f1_": 0.08358639461309555, "f1_overlap_": 0.003212469772290498, "precision_": 0.04741821366428135, "recall_": 0.3523116438356164}

**Comment by ToddLynn** [comment]
您也有尝试将语料换成CMeIE的数据进行测试么？最新的效果有提升么

**Comment by ToddLynn** [comment]
> 我把语料换成中文数据集CMEIE，预训练模型bert-base-Chineseese，为什么效果这么差，pure F值还能达到0.6呢， 下面是pl-marker ner结果 {“dev_best_f1”： 0.08358639461309555， “f1_”： 0.08358639461309555， “f1_overlap_”： 0.003212469772290498， “precision_”： 0.04741821366428135， “recall_”： 0.3523116438356164}

您也有尝试将语料换成CMeIE的数据进行测试么？最新的效果有提升么请问

**Comment by ToddLynn** [comment]
> 我把语料换成中文数据集CMEIE，预训练模型bert-base-Chineseese，为什么效果这么差，pure F值还能达到0.6呢， 下面是pl-marker ner结果 {“dev_best_f1”： 0.08358639461309555， “f1_”： 0.08358639461309555， “f1_overlap_”： 0.003212469772290498， “precision_”： 0.04741821366428135， “recall_”： 0.3523116438356164}

810304762

**Comment by YeDeming** [comment]
这个代码没有在中文上进行过实验
