### ISSUE TITLE
P/R/F1 scores reported in results.json and paper

### ISSUE THREAD

**Issue by IllDepence** [thunlp/PL-Marker#59]
Hi,

I ran your model on the provided SciERC data and get results very close to the ones reported in Table 3 of the paper.

I would now like to know how the precision, recall, and F1 scores are calculated given there are multiple entity classes/relation types. Specifically, I’m wondering

1. Is the number reported in the paper and in `results.json` a macro average or a weighted average?
2. Is NIL/NOTA (i.e. a token that is no entity/an entity pair with no relation) part of the calculation?

Thanks :)

**Comment by YeDeming** [comment]
1. weighted average (micro-F1)
2. NIL/NOTA is a part of denominator of the precision calculation .

**Comment by IllDepence** [comment]
thanks for the super fast reply

**Comment by IllDepence** [comment]
Quick follow-up question, just to make sure I understand correctly.

Regarding

> NIL/NOTA is a part of denominator of the precision calculation

if we think of a scenario where we have entity classes A and B, then we have a false positive for class A *not only* when a B-entity is classified as A, *but also* when a token that is not an entity is classified as A, correct?

What is not clear to me is if you treat NIL/NOTA as a class itself. I.e, if a token that is not an entity is correctly predicted as not an entity, does this count as a true positive?

Thanks again for the clarification.

**Comment by IllDepence** [comment]
@YeDeming ping (just in case there’s not no notifications for comments)
