### ISSUE TITLE
CUDA out of memory 

### ISSUE THREAD

**Issue by Dimiftb** [thunlp/PL-Marker#7]
Hi there, 

I keep getting out of memory issue when attempting to evaluate the models on CoNLl. I've reduced to `batch_size=1` and still I'm unable to train as I get the out of memory error. I'm running 8GB Nvidia Quadro RTX 4000, so I should definitely have space in memory for at least 1 batch per it. Do you know what else I can do to reduce required memory during training? 

Thank you very much.

Here's the error message as well, in case that helps: 

![image](https://user-images.githubusercontent.com/26279721/145042508-df8596dc-dc4a-4792-a070-4c34dd00805b.png)

**Comment by YeDeming** [comment]
Hi,

You can set the --max_pair_length from 256 to 128, which would get  similiar performance.

Or cut down the --max_seq_length from 512  to 384/256.

Best,
Deming

**Comment by Dimiftb** [comment]
Thanks Daming. 

I tried with `--max_pair_length 32` and `--max_seq_length 32`, however still getting the OOM error only after 6 secs of training. I'm guessing I can't really decrease them much more without significantly decreasing performance as well. Do you have any other ideas? 

Best
Dimitar

**Comment by YeDeming** [comment]
The actual sequence length =  max_seq_length + max_pair_length*2.  We use a 40GB Nvidia A100 GPU to run the experiments on the large model.  I suggest that you use the roberta-base model instead of the roberta-large model for efficient experiements.

**Comment by YeDeming** [comment]
We upload our trained models on flat NER datasets on  [Tsinghua Cloud](https://cloud.tsinghua.edu.cn/d/5e4a117bc0e5407b9cee/). We can run a trained NER model in a tiny CUDA memory for inference.
