### ISSUE TITLE
Paramaters

### ISSUE THREAD

**Issue by jingsongs** [thunlp/PL-Marker#8]
您好：
          可以对ner和re部分的参数做一个详细解释吗？好多参数都不知道是用来做什么的，例如：
                      parser.add_argument('--lminit', action='store_true')
                      parser.add_argument('--no_sym', action='store_true')
                      parser.add_argument('--att_left', action='store_true')
                      parser.add_argument('--att_right', action='store_true')

**Comment by YeDeming** [comment]
你好，

--lminit 对应论文中的prompt初始化，即用有意义的词初始化marker
no_sym 去掉对称关系，用来做ablation study
后面两个是随意调的时候设置的，没有用处

祝好
