### ISSUE TITLE
关于`run_ner.py`的疑问

### ISSUE THREAD

**Issue by lairunlin** [thunlp/PL-Marker#9]
`run_ner.py`中第221行到238行主要是为了获取`target_tokens `，能不能麻烦解释一下其中的逻辑？为什么要这么处理？其中涉及到的`half_context_length`、`left_context_length`、`right_context_length`都表示什么意思？非常感谢。
https://github.com/thunlp/PL-Marker/blob/b4863d47e2197b8d410e3d693d684707df9df2a1/run_ner.py#L221-L238

**Comment by YeDeming** [comment]
你好，这是以这个句子为中心，向左和向右取上下文信息拼接，且尽量保持均分，把待处理的句子放在正中间。

**Comment by lairunlin** [comment]
> 你好，这是以这个句子为中心，向左和向右取上下文信息拼接，且尽量保持均分，把待处理的句子放在正中间。

搜噶，晓得了。非常感谢。

**Comment by Pobby321** [comment]
right_context_length = min(right_length, max_num_subwords - left_context_length - sentence_length)

**Comment by YeDeming** [comment]
不是的，你可以实际测试一下，就是向左和向右取相同长度

**Comment by Pobby321** [comment]
max_num_subwords  >= len(subwords) 
left_context_length + sentence_length <= doc_sent_end 
那么min（a,b）中a是恒小于b的

**Comment by YeDeming** [comment]
bert处理的长度限制max_num_subwords 不一定大于 文本token数量len(subwords)

**Comment by Pobby321** [comment]
好，懂了，但是什么情况下需要向左和向右取上下文信息拼接
